### ISSUE TITLE
Remove unnecesary Gmail permissions

### ISSUE THREAD

**Issue by zunjae** [zunjae/KanonApp#2]
Kanon will be able to see the users profile info like name and image upon authorization. That's that's not required by Kanon in order to function. This information is also not fetched. Any idea how to remove this permission?

It's a minor privacy issue that Kanon _can_ see this.

Using the Google login without additional scopes doesn't seem to work

**Comment by RBeze58** [comment]
That's how the Google Secure Sign-In works. To even let the app just sign-in you'll have to share your name and picture and basic information of your profile to the app. It's a problem with their api.

**Comment by zunjae** [comment]
Alright, thanks for letting me know.

I am considering to add more login providers later. Adding support for username/password seems very difficult. I don't want to be responsible for saving (encrypted) passwords. I also don't know how recovering password works. Guess this needs more research
